export interface VocabWord {
  word: string;
  /** concise gloss, used for the offline quiz + as a fallback definition */
  meaning: string;
}

/**
 * Curated intermediate vocabulary. Bundled (not fetched) so the daily set and
 * the quiz work offline and instantly; richer example sentences are fetched
 * from the free Dictionary API on demand.
 */
export const VOCAB: VocabWord[] = [
  { word: "abundant", meaning: "existing in large quantities; plentiful" },
  { word: "accurate", meaning: "correct and without mistakes" },
  { word: "acquire", meaning: "to get or obtain something" },
  { word: "adapt", meaning: "to change to fit a new situation" },
  { word: "adequate", meaning: "enough for a particular purpose" },
  { word: "ambiguous", meaning: "having more than one possible meaning" },
  { word: "anticipate", meaning: "to expect something to happen" },
  { word: "apparent", meaning: "clear and easy to see or understand" },
  { word: "appreciate", meaning: "to value or be grateful for something" },
  { word: "approach", meaning: "a way of dealing with something" },
  { word: "appropriate", meaning: "suitable for a situation" },
  { word: "assess", meaning: "to judge the quality or value of something" },
  { word: "assume", meaning: "to accept as true without proof" },
  { word: "attempt", meaning: "to try to do something" },
  { word: "attitude", meaning: "a way of thinking or feeling about something" },
  { word: "authentic", meaning: "genuine and real, not fake" },
  { word: "aware", meaning: "knowing that something exists" },
  { word: "benefit", meaning: "an advantage or helpful result" },
  { word: "brief", meaning: "lasting a short time; short" },
  { word: "capable", meaning: "able to do something" },
  { word: "cautious", meaning: "careful to avoid problems or danger" },
  { word: "challenge", meaning: "a difficult task that tests ability" },
  { word: "circumstance", meaning: "a condition or fact affecting a situation" },
  { word: "collapse", meaning: "to fall down or fail suddenly" },
  { word: "commit", meaning: "to promise or dedicate yourself to something" },
  { word: "complex", meaning: "having many connected parts; complicated" },
  { word: "comprehend", meaning: "to understand something fully" },
  { word: "conceal", meaning: "to hide something" },
  { word: "confident", meaning: "sure about your own ability" },
  { word: "consequence", meaning: "a result of an action or situation" },
  { word: "consistent", meaning: "always behaving in the same way" },
  { word: "constant", meaning: "happening all the time; not changing" },
  { word: "contribute", meaning: "to give something to help a result" },
  { word: "convince", meaning: "to make someone believe something" },
  { word: "crucial", meaning: "extremely important" },
  { word: "curious", meaning: "eager to know or learn something" },
  { word: "decline", meaning: "to become less or to politely refuse" },
  { word: "dedicate", meaning: "to give time and effort to something" },
  { word: "delicate", meaning: "easily damaged; needing careful handling" },
  { word: "demonstrate", meaning: "to show clearly by example" },
  { word: "deny", meaning: "to say that something is not true" },
  { word: "deserve", meaning: "to earn something by your actions" },
  { word: "determine", meaning: "to decide or find out exactly" },
  { word: "diligent", meaning: "working hard and carefully" },
  { word: "diminish", meaning: "to become or make smaller" },
  { word: "distinct", meaning: "clearly different or separate" },
  { word: "diverse", meaning: "made of many different kinds" },
  { word: "efficient", meaning: "working well without wasting time or effort" },
  { word: "elaborate", meaning: "detailed and complicated" },
  { word: "eliminate", meaning: "to remove or get rid of something" },
  { word: "emerge", meaning: "to come out or become known" },
  { word: "emphasize", meaning: "to give special importance to something" },
  { word: "encounter", meaning: "to meet or experience unexpectedly" },
  { word: "endure", meaning: "to suffer something patiently; to last" },
  { word: "enhance", meaning: "to improve the quality of something" },
  { word: "enormous", meaning: "extremely large" },
  { word: "essential", meaning: "absolutely necessary" },
  { word: "estimate", meaning: "to guess an approximate value" },
  { word: "evident", meaning: "clear and obvious" },
  { word: "exhaust", meaning: "to make very tired or to use up completely" },
  { word: "expand", meaning: "to become larger" },
  { word: "explicit", meaning: "stated clearly and in detail" },
  { word: "fascinate", meaning: "to attract and hold interest strongly" },
  { word: "feasible", meaning: "possible to do easily" },
  { word: "flexible", meaning: "able to change or bend easily" },
  { word: "fluent", meaning: "able to speak a language smoothly" },
  { word: "fundamental", meaning: "forming a necessary base; basic" },
  { word: "generate", meaning: "to produce or create something" },
  { word: "genuine", meaning: "real and honest, not fake" },
  { word: "gradual", meaning: "happening slowly over time" },
  { word: "hesitate", meaning: "to pause before doing something" },
  { word: "hostile", meaning: "unfriendly and aggressive" },
  { word: "humble", meaning: "not proud; modest" },
  { word: "identify", meaning: "to recognize or name something" },
  { word: "immense", meaning: "extremely large in size or degree" },
  { word: "implement", meaning: "to put a plan into action" },
  { word: "imply", meaning: "to suggest without saying directly" },
  { word: "inevitable", meaning: "certain to happen; unavoidable" },
  { word: "influence", meaning: "the power to affect someone or something" },
  { word: "initial", meaning: "happening at the beginning; first" },
  { word: "innovative", meaning: "introducing new ideas or methods" },
  { word: "intense", meaning: "very strong or extreme" },
  { word: "interpret", meaning: "to explain the meaning of something" },
  { word: "isolate", meaning: "to separate from others" },
  { word: "justify", meaning: "to show that something is reasonable" },
  { word: "maintain", meaning: "to keep something in good condition" },
  { word: "modest", meaning: "not large; humble about yourself" },
  { word: "negotiate", meaning: "to discuss to reach an agreement" },
  { word: "obstacle", meaning: "something that blocks progress" },
  { word: "obvious", meaning: "easy to see or understand" },
  { word: "occur", meaning: "to happen or take place" },
  { word: "persist", meaning: "to continue firmly despite difficulty" },
  { word: "precise", meaning: "exact and accurate" },
  { word: "predict", meaning: "to say what will happen in the future" },
  { word: "prominent", meaning: "important and well known" },
  { word: "reluctant", meaning: "unwilling and hesitant" },
  { word: "resemble", meaning: "to look or be similar to" },
  { word: "reveal", meaning: "to make known something hidden" },
  { word: "significant", meaning: "large or important enough to matter" },
  { word: "sufficient", meaning: "as much as is needed" },
  { word: "tremendous", meaning: "very great in amount or degree" },
  { word: "versatile", meaning: "able to do many different things well" },
  { word: "vivid", meaning: "producing strong, clear images in the mind" },
];
