import { defineSchema } from "@/core/settings-engine/schema";

export const wallpaperSettingsSchema = defineSchema({
  mode: {
    type: "select",
    label: "wallpaper.mode",
    description: "wallpaper.modeDesc",
    options: [
      { value: "static", label: "wallpaper.modeStatic" },
      { value: "slideshow", label: "wallpaper.modeSlideshow" },
    ],
    default: "static",
  },
  slideInterval: {
    type: "slider",
    label: "wallpaper.slideInterval",
    description: "wallpaper.slideIntervalDesc",
    min: 5,
    max: 300,
    step: 5,
    default: 30,
    showIf: (v) => v.mode === "slideshow",
  },
  slideOrder: {
    type: "select",
    label: "wallpaper.slideOrder",
    options: [
      { value: "sequential", label: "wallpaper.slideSequential" },
      { value: "random", label: "wallpaper.slideRandom" },
    ],
    default: "sequential",
    showIf: (v) => v.mode === "slideshow",
  },
  randomMode: {
    type: "select",
    label: "wallpaper.randomMode",
    description: "wallpaper.randomModeDesc",
    options: [
      { value: "wallhaven", label: "wallpaper.randomWallhaven" },
      { value: "off", label: "wallpaper.randomOff" },
      { value: "images", label: "wallpaper.randomImages" },
      { value: "videos", label: "wallpaper.randomVideos" },
      { value: "all", label: "wallpaper.randomAll" },
    ],
    default: "wallhaven",
    showIf: (v) => v.mode !== "slideshow",
  },
  wallhavenTopic: {
    type: "select",
    label: "wallpaper.wallhavenTopic",
    description: "wallpaper.wallhavenTopicDesc",
    options: [
      { value: "all", label: "wallpaper.topicAll" },
      { value: "space", label: "wallpaper.topicSpace" },
      { value: "forest", label: "wallpaper.topicForest" },
      { value: "city", label: "wallpaper.topicCity" },
      { value: "landscape", label: "wallpaper.topicLandscape" },
    ],
    default: "all",
    showIf: (v) => v.randomMode === "wallhaven" && v.mode !== "slideshow",
  },
  wallhavenResolution: {
    type: "select",
    label: "wallpaper.wallhavenMinRes",
    options: [
      { value: "2560x1440", label: "2K QHD (2560x1440+)" },
      { value: "3840x2160", label: "4K UHD (3840x2160+)" },
    ],
    default: "2560x1440",
    showIf: (v) => v.randomMode === "wallhaven" && v.mode !== "slideshow",
  },
  wallhavenCategory: {
    type: "select",
    label: "wallpaper.wallhavenCategory",
    options: [
      { value: "all", label: "wallpaper.catAll" },
      { value: "general", label: "wallpaper.catGeneral" },
      { value: "anime", label: "wallpaper.catAnime" },
      { value: "people", label: "wallpaper.catPeople" },
    ],
    default: "all",
    showIf: (v) => v.randomMode === "wallhaven" && v.mode !== "slideshow",
  },
  wallhavenCustomQuery: {
    type: "text",
    label: "wallpaper.wallhavenCustomQuery",
    description: "wallpaper.wallhavenCustomQueryDesc",
    default: "",
    showIf: (v) => v.randomMode === "wallhaven" && v.mode !== "slideshow",
  },
  videoSound: { type: "toggle", label: "wallpaper.videoSound", default: false },
  videoVolume: {
    type: "slider",
    label: "wallpaper.videoVolume",
    min: 1,
    max: 100,
    step: 1,
    default: 50,
    showIf: (v) => v.videoSound === true,
  },
  pauseWhenHidden: {
    type: "toggle",
    label: "wallpaper.pauseWhenHidden",
    description: "wallpaper.pauseWhenHiddenDesc",
    default: true,
  },
});
